routes:
  - upstream: "127.0.0.1:9091"
    patterns:
    - "^(?:[a-zA-Z0-9-]+\\.)*ifconfig\\.me$"
  - upstream: "127.0.0.1:9090"
    patterns:
    - "^(?:[a-zA-Z0-9-]+\\.)*ipify\\.org$"
    - "icanhazip.com"
