routes:
  - upstream: "127.0.0.1:9091"
    command: "ssh -N -D9091 ubuntu@34.196.56.211"
    matches:
      regex:
        - "^(?:[a-zA-Z0-9-]+\\.)*ifconfig\\.me$"
  - upstream: "127.0.0.1:9090"
    command: "ssh -N -D9090 darius@plex"
    matches:
      regex:
        - "^(?:[a-zA-Z0-9-]+\\.)*ipify\\.org$"
        - "icanhazip.com"
      cidr: 
        - 10.0.0.0/24
