routes:
  - upstream: "127.0.0.1:9091"
    match:
      regex:
        - "^(?:[a-zA-Z0-9-]+\\.)*ifconfig\\.me$"
  - upstream: "127.0.0.1:9090"
    match:
      regex:
        - "^(?:[a-zA-Z0-9-]+\\.)*ipify\\.org$"
        - "icanhazip.com"
      cidr: 
        - 10.0.0.0/24
